# Could be generated by the lab project if definintion of interactive groups change
module GroupStore
  extend ActiveSupport::Concern

  module ClassMethods
    # find the model where the json_rep['path'] == path
    def find_by_path(path)
      find do |g|
        g if g.json_rep['path'] == path
      end
    end
  end

  module InstanceMethods
  end

  included do
    store :json_rep, :accessors => [:name, :path, :category]
  end
end
