# Generated by bin/gen_interactive_attrs.rb
# Depends on the definition of interactive in the lab project

# just use this in the Interactive AR model
module InteractiveStore
  extend ActiveSupport::Concern

  module ClassMethods
    # find the model where the json_rep['path'] == path
    def find_by_path(path)
      find do |g|
        g if g.json_rep['path'] == path
      end
    end
  end

  module InstanceMethods
  end

  included do
    # GENERATED
      store :json_rep, :accessors => [:title, :path, :groupKey, :subtitle, :about, :publicationStatus, :fontScale, :models, :parameters, :outputs, :filteredOutputs, :exports, :components, :layout, :template]
    # GENERATED
  end
end
