# Generated by $ rails generate interactive_store on 18 Jul 2013 16:07:49PM
# Depends on the definition of interactive metadata in the lab project

# just use this in the Interactive AR model
module InteractiveStore
  extend ActiveSupport::Concern

  module ClassMethods
  end

  module InstanceMethods
  end

  included do
      serialize :json_rep, Surus::Hstore::Serializer.new
      store_accessor :json_rep, :title, :publicationStatus, :subtitle, :about, :importedFrom, :fontScale, :models, :parameters, :outputs, :filteredOutputs, :exports, :components, :layout, :template
  end
end
