# Generated by $ rails generate interactive_store
# Depends on the definition of interactive in the lab project

# just use this in the Interactive AR model
module InteractiveStore
  extend ActiveSupport::Concern

  module ClassMethods
  end

  module InstanceMethods
  end

  included do
    # GENERATED
      store :json_rep, :accessors => [:title, :publicationStatus, :subtitle, :about, :importedFrom, :fontScale, :models, :parameters, :outputs, :filteredOutputs, :exports, :components, :layout, :template]
    # GENERATED
  end
end
