# Generated by $ rails generate download_lab

module LabHostSettings

  def setup_lab_server
    # GENERATED at 11 Jul 2013 17:07:58PM
    @remote_host = 'lab.dev.concord.org'
    @remote_port = '80'
    @lab_version = '2666763'
    @lab_path_prefix = 'version'

    # GENERATED
  end
end
