development:
  adapter: postgresql
  encoding: unicode
  database: lab-interactive-management_development
  pool: 5
  username: tdyer
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: lab-interactive-management_test
  pool: 5
  username: tdyer
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: lab-interactive-management_production
  pool: 5
  username: tdyer
  password:
