# Generated by `$ rails generate lab:models` on 16 Jul 2013 16:07:01PM
# Depends on the definition of the energy2d model type in the lab project
# GENERATED
class Energy2d < ActiveRecord::Base

  store :json_rep, :accessors => [:viewOptions, :part, :sensor, :use_WebGL, :grid_width, :grid_height, :model_width, :model_height, :timeStep, :timeStepsPerTick, :ticksPerGPUSync, :convective, :background_temperature, :background_conductivity, :background_specific_heat, :background_density, :background_viscosity, :thermal_buoyancy, :buoyancy_approximation, :boundary, :measurement_interval, :viewupdate_interval, :stoptime, :sunny, :sun_angle, :solar_power_density, :solar_ray_count, :solar_ray_speed, :photon_emission_interval, :structure, :url]

  def gen_new_url
    self.url = json_rep['url'].gsub("/","_").gsub('$','_').gsub(/^_/,"").gsub('.json','')
  end

  def gen_image_path
    self.json_rep['imagePath'] = self.json_rep['url'].gsub(/^\//, '').match(/.*\//)[0];
  end

  def self.find_by_url(url)
    find do |g|
      g if g.json_rep['url'] == url
    end
  end

  def presenter
    # trickery to get the serialized attribute, json_rep, to show up
    # as if its a top level attribute
    json_rep_hash = self.json_rep
    # here's the models, not serialized, attributes
    presenter_hash = self.attributes.delete('json_rep')
    presenter_hash.merge(json_rep)
  end

end
# GENERATED