# Generated by `$ rails generate lab:models` on 16 Jul 2013 16:07:04PM
# Depends on the definition of the signal-generator model type in the lab project
# GENERATED
class SignalGenerator < ActiveRecord::Base

  store :json_rep, :accessors => [:viewOptions, :frequency, :modelSampleRate, :timeScale, :url]

  def gen_new_url
    self.url = json_rep['url'].gsub("/","_").gsub('$','_').gsub(/^_/,"").gsub('.json','')
  end

  def gen_image_path
    self.json_rep['imagePath'] = self.json_rep['url'].gsub(/^\//, '').match(/.*\//)[0];
  end

  def self.find_by_url(url)
    find do |g|
      g if g.json_rep['url'] == url
    end
  end

  def presenter
    # trickery to get the serialized attribute, json_rep, to show up
    # as if its a top level attribute
    json_rep_hash = self.json_rep
    # here's the models, not serialized, attributes
    presenter_hash = self.attributes.delete('json_rep')
    presenter_hash.merge(json_rep)
  end

end
# GENERATED